"""create user table v1.1

Revision ID: ed5fe6d77f59
Revises: ace9e0070903
Create Date: 2024-08-05 19:44:09.474286

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ed5fe6d77f59"
down_revision: Union[str, None] = "ace9e0070903"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("email", sa.String(), nullable=False))
    op.add_column("user", sa.Column("password", sa.String(), nullable=False))
    op.add_column("user", sa.Column("age", sa.Integer(), nullable=False))
    op.drop_constraint("user_username_key", "user", type_="unique")
    op.create_unique_constraint(op.f("uq_user_email"), "user", ["email"])
    op.create_unique_constraint(op.f("uq_user_username"), "user", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_user_username"), "user", type_="unique")
    op.drop_constraint(op.f("uq_user_email"), "user", type_="unique")
    op.create_unique_constraint("user_username_key", "user", ["username"])
    op.drop_column("user", "age")
    op.drop_column("user", "password")
    op.drop_column("user", "email")
    # ### end Alembic commands ###
